// let a = 4;
// let b = 9;

// let ans = a * b;

// console.log(ans);

// let myName = "Xavi"
// myName += "Pashley"

// console.log(myName);

// let favouriteDrink = "coffee";

// console.log("My favourite drink is " + favouriteDrink);

// let myName = 'Xavi';
// let age = 21;
// let favDrink = 'Red Wine';
// console.log("Hi my name is " + myName + ". I am " + age + "years old. I like to drink " + favDrink+ "."
// +favDrink+".");
// console.log(`Hi my name is  ${myName} . I am  ${age}  years old. I like to drink  ${favDrink}.`)


// LOG FRIENDS
// let Friend1 = 'Xavi';
// let Age1 = 21;
// let Drink1 = 'Red Wine';
// console.log(`Hi my name is  ${Friend1} . I am  ${Age1}  years old. I like to drink  ${Drink1} on a Sunday night.`)

// let Friend2 = 'Safeer'
// let Age2 = 26;
// let Drink2 = 'CocaCola';
// console.log(`Hi my name is ${Friend2} . I am ${Age2} years old. I like to drink ${Drink2} in the summer sun.`)

// let Friend3 = 'Nora'
// let Age3 = 21;
// let Drink3 = 'Hot Chocolate';
// console.log(`Hi my name is ${Friend3} . I am ${Age3} years old. I like to drink ${Drink3} when it gets cold.`)


// LOG Days to Birthday
// let dateToday = new Date();
// let myBirthdate = new Date('2024, 11, 5');
 
// let milliseconds = myBirthdate - dateToday;
// milliseconds = milliseconds / 1000;
// milliseconds /= 60;
// milliseconds /= 60;
// milliseconds /= 24;
 
// console.log(`You have ${Math.floor(milliseconds)} days to go until our birthday`);

// let place = "Manc";
// let weather = "Cloudy";

// if (place == "Manc && weather == "Sunny") {
// console.log(Check again");
// }
//  else if (place == "Manc" && weather == "Rain") }
//  console.log("Obvs);
// }
// else {
// console.log("What it isn't raining?");    
// }

// Activity 1

// let age = 16
// if (age < 18) {
//     console.log('too young')
// } else {
//     console.log('Old enough')
// }  

// Activity 2

